export const ARTICLE_ERRORS = {
  unauthorized: "אין הרשאה לבצע פעולה זו.",
  generic: "אירעה שגיאה. נסו שוב מאוחר יותר.",
  notFound: "הפוסט לא נמצא.",
  slugTaken: "כתובת הפוסט כבר בשימוש.",
  coverRequired: "יש לבחור תמונת כיסוי.",
  coverRequiredPublish: "תמונת כיסוי נדרשת לפרסום.",
  mediaNotFound: "התמונה שנבחרה לא נמצאה.",
  categoryRequired: "יש לבחור קטגוריה.",
  categoryInvalid: "ניתן לבחור רק קטגוריות פוסטים.",
  categoryMissing: "אין קטגוריות פוסטים במערכת. יש ליצור קטגוריה לפני פרסום.",
  tagInvalid: "ניתן לבחור רק תגיות פוסטים.",
  contentRequired: "יש להוסיף תוכן לפוסט.",
  archiveOnlyDelete: "ניתן למחוק לצמיתות רק פוסט בארכיון.",
  duplicateFailed: "שכפול הפוסט נכשל.",
  galleryLimit: "ניתן להוסיף עד 6 תמונות לגלריה.",
} as const;
