import {
  applySlugSuffix,
  containsHebrew,
  parseSlugSuffix,
  slugifyHebrewTitle,
} from "@/lib/slug/hebrew-slug";
import { legacySlugifyTitle } from "@/lib/slug/legacy-transliteration";

export type SlugMigrationDecision =
  | { action: "skip"; reason: "already_hebrew" | "manual_latin" }
  | { action: "migrate"; newSlug: string; reason: "auto_latin" };

export function classifySlugForMigration(input: {
  slug: string;
  title: string;
  fallback: string;
}): SlugMigrationDecision {
  if (containsHebrew(input.slug)) {
    return { action: "skip", reason: "already_hebrew" };
  }

  if (!isAutoGeneratedLatinSlug(input.slug, input.title, input.fallback)) {
    return { action: "skip", reason: "manual_latin" };
  }

  const suffix = parseSlugSuffix(input.slug);
  const hebrewBase = slugifyHebrewTitle(input.title, input.fallback);

  return {
    action: "migrate",
    reason: "auto_latin",
    newSlug: applySlugSuffix(hebrewBase, suffix),
  };
}

export function isAutoGeneratedLatinSlug(
  slug: string,
  title: string,
  fallback: string
): boolean {
  const suffix = parseSlugSuffix(slug);
  const expectedBase = legacySlugifyTitle(title, fallback);

  if (suffix.base === expectedBase) {
    return true;
  }

  if (suffix.copySuffix && suffix.base === expectedBase) {
    return true;
  }

  return false;
}
